apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  destination:
    namespace: grafana
    server: https://kubernetes.default.svc
  project: smarthome
  sources:
  - repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.58.7
    chart: grafana
    helm:
      values: |
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt
          hosts: 
          - grafana.k8s.lan
          - grafana.rock.k8s.vogelherdweg.de
          - grafana.internal.k8s.vogelherdweg.de
          tls: 
          - hosts: 
            - grafana.rock.k8s.vogelherdweg.de
            - grafana.internal.k8s.vogelherdweg.de
            secretName: grafana-rock-k8s-vogelherdweg-de-tls
        admin:
          existingSecret: grafana-secret
        datasources:
          datatasources.yaml:
            apiVersion: 1
            datasources:
            - name: InfluxDB
              type: influxdb 
              url: "https://influx.rock.k8s.vogelherdweg.de"
              jsonData:
                version: Flux
                organization: "influxdata"
                defaultBucket: default
              secureJsonData: 
                token: "$INFLUX_TOKEN"
        envValueFrom:
          INFLUX_TOKEN:
            secretKeyRef:
              name: influxdb-secret
              key: admin-token
        dashboardProviders:
          dashboardproviders.yaml:
            apiVersion: 1
            providers:
            - name: 'default'
              orgId: 1
              folder: ''
              type: file
              disableDeletion: false
              editable: true
              options:
                path: /var/lib/grafana/dashboards/default
        dashboards:
          default:
            environment:
              url: https://gist.githubusercontent.com/MyChaOS87/6e0fcaf0cf929e3a6add87f5b22a8b53/raw/b6618cfadc10f93f3bd38329c87025fb724d031d/Environment.json
            power:
              url: https://gist.githubusercontent.com/MyChaOS87/6e0fcaf0cf929e3a6add87f5b22a8b53/raw/b6618cfadc10f93f3bd38329c87025fb724d031d/Power.json
  - repoURL: git@github.com:MyChaOS87/sloth.git
    targetRevision: feature/rock5b
    path: deployments/smarthome/grafana-secrets
  - repoURL: git@github.com:MyChaOS87/sloth.git
    targetRevision: feature/rock5b
    path: deployments/smarthome/influxdb-secrets
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true