apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: influxdb
  namespace: argocd
spec:
  destination:
    namespace: influxdb
    server: https://kubernetes.default.svc
  project: smarthome
  sources:
  - repoURL: https://helm.influxdata.com/
    targetRevision: 2.1.2
    chart: influxdb2
    helm:
      values: |
        persistence:
          enabled: true
          size: 5Gi
          storageClass: longhorn
        ingress:
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt
          enabled: true
          hostname: influx.rock.k8s.vogelherdweg.de
          tls: true
          secretName: influx-rock-k8s-vogelherdweg-de-tls
        adminUser:
          organization: "influxdata"
          bucket: "default"
          user: "admin"
          existingSecret: influxdb-secret
        config:
          http: 
            auth-enabled: true
  - repoURL: git@github.com:MyChaOS87/sloth.git
    targetRevision: feature/rock5b
    path: deployments/smarthome/influxdb-secrets
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true