apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mosquitto
  namespace: argocd
spec:
  destination:
    namespace: mosquitto
    server: https://kubernetes.default.svc
  project: smarthome
  source:
    repoURL: git@github.com:MyChaOS87/sloth.git
    targetRevision: feature/rock5b
    path: deployments/smarthome/mosquitto
    helm:
      values: |
        service:
          annotations:
            metallb.universe.tf/loadBalancerIPs: 192.168.1.30
            external-dns.alpha.kubernetes.io/hostname: mosquitto.rock.k8s.vogelherdweg.de,mosquitto.internal.k8s.vogelherdweg.de.
          type: LoadBalancer
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true