---
apiVersion: v1
kind: Namespace
metadata:
  name: grafana
---
apiVersion: v1
kind: Namespace
metadata:
  name: influxdb
---
apiVersion: v1
kind: Namespace
metadata:
  name: mosquitto
---
apiVersion: v1
kind: Namespace
metadata:
  name: telegraf
--- 
apiVersion: v1
kind: Namespace
metadata:
  name: automqttion
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: smarthome
  namespace: argocd
spec:
  description: access to the used namespaces for cluster essentials
  sourceRepos:
  - '*'
  destinations:
  - namespace: grafana
    server: https://kubernetes.default.svc
  - namespace: influxdb
    server: https://kubernetes.default.svc  
  - namespace: mosquitto
    server: https://kubernetes.default.svc
  - namespace: telegraf
    server: https://kubernetes.default.svc
  - namespace: automqttion
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  orphanedResources:
    warn: false