apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: influxdb
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: influxdb
    server: https://kubernetes.default.svc
  orphanedResources:
    warn: false
  sourceRepos:
  - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: influx-secrets
  namespace: argocd
spec:
  destination:
    namespace: influxdb
    server: https://kubernetes.default.svc
  project: influxdb
  source:
    repoURL: git@github.com:MyChaOS87/sloth.git
    targetRevision: HEAD
    path: deployments/influx-secrets
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: influxdb
  namespace: argocd
spec:
  destination:
    namespace: influxdb
    server: https://kubernetes.default.svc
  project: influxdb
  source:
    repoURL: https://helm.influxdata.com/
    targetRevision: 2.1.1
    chart: influxdb2
    helm:
      values: |
        persistence:
          enabled: true
          size: 5Gi
          storageClass: longhorn
        ingress:
          enabled: true
          hostname: influx.k8s.lan
        setDefaultUser:
          enabled: true
        config:
          http: 
            auth-enabled: true
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: telegraf
  namespace: argocd
spec:
  destination:
    namespace: influxdb
    server: https://kubernetes.default.svc
  project: influxdb
  source:
    repoURL: https://helm.influxdata.com/
    targetRevision: 1.8.24
    chart: telegraf
    helm:
      parameters:
        - name: tplVersion
          value: "2"
      values: |
        image:
          tag: "1.25"
        service:
          enabled: false
        config:
          agent:
            debug: true
          processors:
          outputs:
            - influxdb_v2:
                urls:
                  - "https://influx.k8s.lan"
                token: "${INFLUX_TOKEN}"
                organization: "influxdata"
                bucket: "default"
                insecure_skip_verify: true
          inputs:
            - mqtt_consumer:
                servers:
                  - "tcp://mosquitto.k8s.lan:1883"
                topics: 
                  - "shellies/+/+/+/power"
                  - "shellies/+/+/+/energy"
                  - "shellies/+/+/+/voltage"
                  - "shellies/+/+/+/current"
                  - "shellies/+/sensor/temperature"
                  - "shellies/+/sensor/humidity"
                  - "shellies/+/sensor/battery"
                data_format: "value"
                data_type: "float"
                topic_parsing:
                  - topic: "shellies/+/+/+/+"
                    measurement: "_/_/_/_/measurement"
                    tags: "_/shelly_id/shelly_type/sub_id/_"
                  - topic: "shellies/+/sensor/+"
                    measurement: "_/_/_/measurement"
                    tags: "_/shelly_id/shelly_type/_"
            - mqtt_consumer:
                servers:
                  - "tcp://mosquitto.k8s.lan:1883"
                topics: 
                  - "warp2/22hg/meter/values"
                data_format: "json_v2"
                topic_parsing:
                  - topic: "warp2/22hg/meter/values"
                    tags: "_/wallbox_name/_/_"
                json_v2:
                  - measurement_name: "power"
                    field:
                      - path: "power"
                        type: "float"
        env:        
          - name: INFLUX_TOKEN
            valueFrom: 
              secretKeyRef:
                name: influxdb-influxdb2-auth
                key: admin-token
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  destination:
    namespace: influxdb
    server: https://kubernetes.default.svc
  project: influxdb
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.50.1
    chart: grafana
    helm:
      values: |
        ingress:
          enabled: true
          hosts: 
          - grafana.k8s.lan
        admin:
          existingSecret: grafana-secret
        datasources:
          datatasources.yaml:
            apiVersion: 1
            datasources:
            - name: InfluxDB
              type: influxdb 
              url: "https://influx.k8s.lan"
              jsonData:
                version: Flux
                organization: "influxdata"
                defaultBucket: default
                tlsSkipVerify: true
              secureJsonData: 
                token: "$INFLUX_TOKEN"
        envValueFrom:
          INFLUX_TOKEN:
            secretKeyRef:
              name: influxdb-influxdb2-auth
              key: admin-token
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
