---
apiVersion: v1
kind: Namespace
metadata:
  name: paperlessngx-dms
---
apiVersion: v1
kind: Namespace
metadata:
  name: redis-dms
---
apiVersion: v1
kind: Namespace
metadata:
  name: postgres-dms
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dms
  namespace: argocd
spec:
  description: access to the used namespaces for dms
  sourceRepos:
  - '*'
  destinations:
  - namespace: paperlessngx-dms
    server: https://kubernetes.default.svc
  - namespace: redis-dms
    server: https://kubernetes.default.svc
  - namespace: postgres-dms
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  orphanedResources:
    warn: false
