apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
spec:
  destination:
    namespace: postgres-dms
    server: https://kubernetes.default.svc
  project: dms
  sources:
  - repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 15.5.20
    chart: postgresql
    helm:
      values: |
        nameOverride: postgres-paperless
        global:
          defaultStorageClass: longhorn
        auth:
          enabled: true
          existingSecret: postgres-secret
          username: paperless
          database: paperless
          secretKeys:
            adminPasswordKey: admin-password
            userPasswordKey: user-password
            replicationPasswordKey: replication-password
  - repoURL: git@github.com:MyChaOS87/sloth.git
    targetRevision: main
    path: deployments/dms/postgres-secrets
        