apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
spec:
  destination:
    namespace: redis-dms
    server: https://kubernetes.default.svc
  project: dms
  sources:
  - repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 19.6.4
    chart: redis
    helm:
      values: |
        nameOverride: redis-paperless
        auth:
          enabled: true
          existingSecret: redis-secret
          existingSecretPasswordKey: password
        master:
          persistence:
            enabled: true
            size: 5Gi
            storageClass: longhorn
  - repoURL: git@github.com:MyChaOS87/sloth.git
    targetRevision: main
    path: deployments/dms/redis-secrets
        