apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mosquitto.fullname" . }}
  labels:
    {{- include "mosquitto.labels" . | nindent 4 }}
data:
  mosquitto.conf: |-
    listener  {{ .Values.service.port }} 0.0.0.0
    protocol mqtt

    log_dest stdout
    allow_anonymous true
