apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mosquitto.fullname" . }}
  labels:
    {{- include "mosquitto.labels" . | nindent 4 }}
data:
  mosquitto.conf: |-
    listener  {{ .Values.service.port }} 0.0.0.0
    protocol mqtt

    log_dest stdout
    allow_anonymous true

    connection awsiot
    address a2r45j733id3jo-ats.iot.eu-central-1.amazonaws.com:8883
    topic shellies/+/relay/+/power out 1
    topic shellies/+/relay/+/energy out 1
    bridge_insecure false
    cleansession true
    clientid bridgeawsiot
    start_type automatic
    notifications false
    log_type all
    bridge_cafile /etc/mosquitto/certs/awsiot/awsiot.ca.pem
    bridge_certfile /etc/mosquitto/certs/awsiot/awsiot.cert.crt
    bridge_keyfile /etc/mosquitto/certs/awsiot/awsiot.private.key