---
apiVersion: v1
kind: Namespace
metadata:
  name: sealed-secrets
---
apiVersion: v1
kind: Namespace
metadata:
  name: metallb
---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: v1
kind: Namespace
metadata:
  name: external-dns
---
apiVersion: v1
kind: Namespace
metadata:
  name: longhorn
---
apiVersion: v1
kind: Namespace
metadata:
  name: prometheus
---
apiVersion: v1
kind: Namespace
metadata:
  name: version-checker
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster-essentials
  namespace: argocd
spec:
  description: access to the used namespaces for cluster essentials
  sourceRepos:
  - '*'
  destinations:
  - namespace: sealed-secrets
    server: https://kubernetes.default.svc
  - namespace: metallb
    server: https://kubernetes.default.svc  
  - namespace: traefik
    server: https://kubernetes.default.svc
  - namespace: cert-manager
    server: https://kubernetes.default.svc
  - namespace: external-dns
    server: https://kubernetes.default.svc
  - namespace: longhorn
    server: https://kubernetes.default.svc
  - namespace: kube-system
    server: https://kubernetes.default.svc
  - namespace: version-checker
    server: https://kubernetes.default.svc
  - namespace: prometheus
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  orphanedResources:
    warn: false