---
apiVersion: v1
kind: Namespace
metadata:
  name: sealed-secrets
---
apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik-system
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster-essentials
  namespace: argocd
spec:
  description: access to the used namespaces for cluster essentials
  sourceRepos:
  - '*'
  destinations:
  - namespace: sealed-secrets
    server: https://kubernetes.default.svc
  - namespace: metallb-system
    server: https://kubernetes.default.svc  
  - namespace: traefik-system
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  orphanedResources:
    warn: false