apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  source:
    repoURL: https://helm.traefik.io/traefik
    targetRevision: 23.2.0
    chart: traefik
    helm:
      values: |
        providers:
          kubernetesIngress:
            publishedService:
              enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  project: cluster-essentials
  syncPolicy:
    automated:
      prune: true
      selfHeal: true