apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  source:
    repoURL: https://helm.traefik.io/traefik
    targetRevision: 26.0.0
    chart: traefik
    helm:
      values: |
        providers:
          kubernetesIngress:
            publishedService:
              enabled: true
        podAnnotations:
          pin-major.version-checker.io/traefik: 2
        ports:
          web:
            redirectTo: 
              port: websecure
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  project: cluster-essentials
  syncPolicy:
    automated:
      prune: true
      selfHeal: true