apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metallb-auto-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.1.50-192.168.1.99
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metallb-reserved-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.1.30-192.168.1.49
  autoAssign: false
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default-l2advertisement
  namespace: metallb-system