apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  source:
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 7.3.4
    chart: argo-cd
    helm:
      values: |
        dex:
          enabled: false
        configs:
          params: 
            server.insecure: true  
        server:
          ingress:
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt
            enabled: true
            hostname: argocd.internal.k8s.vogelherdweg.de
            extraHosts:
              - name: argocd.rock.k8s.vogelherdweg.de
            tls: true
            extraTls: 
              - hosts: 
                - argocd.internal.k8s.vogelherdweg.de
                - argocd.rock.k8s.vogelherdweg.de
                secretName: argocd-rock-k8s-vogelherdweg-de-tls
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd 
  project: argocd-base
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

