apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  source:
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 5.42.2
    chart: argo-cd
    helm:
      values: |
        dex:
          enabled: false
        configs:
          params: 
            server.insecure: true  
        server:
          ingress:
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt
            enabled: true
            hosts:
              - argocd-rock.k8s.lan   
              - argocd.rock.k8s.vogelherdweg.de
              - argocd.internal.k8s.vogelherdweg.de
            tls: 
            - hosts: 
              - argocd.rock.k8s.vogelherdweg.de
              - argocd.internal.k8s.vogelherdweg.de
              secretName: argocd-rock-k8s-vogelherdweg-de-tls
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd 
  project: argocd-base
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

