apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-base
  namespace: argocd
spec:
  source:
    repoURL: git@github.com:MyChaOS87/sloth.git
    targetRevision: main
    path: argocd-base
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: argocd-base
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd-base
  namespace: argocd
spec:
  description: Argocd Project
  sourceRepos:
  - '*'
  destinations:
  - namespace: argocd
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  orphanedResources:
    warn: false