apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  source:
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 2.11.0
    chart: sealed-secrets
    helm: 
      values: |
        fullnameOverride: sealed-secrets-controller
  destination:
    server: https://kubernetes.default.svc
    namespace: sealed-secrets
  project: sealed-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  description: access to sealed-secrets
  sourceRepos:
  - '*'
  destinations:
  - namespace: sealed-secrets
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  orphanedResources:
    warn: false