apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-internal-k8s-vogelherdweg-de
  namespace: cert-manager
spec:
  secretName: test-internal-k8s-vogelherdweg-de
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: test.internal.k8s.vogelherdweg.de
  dnsNames:
  - test.internal.k8s.vogelherdweg.de
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-rock-k8s-vogelherdweg-de
  namespace: cert-manager
spec:
  secretName: test-rock-k8s-vogelherdweg-de
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: test.rock.k8s.vogelherdweg.de
  dnsNames:
  - test.rock.k8s.vogelherdweg.de