longhorn:
  defaultSettings:
    createDefaultDiskLabeledNodes: true
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    enabled: true
    host: longhorn.internal.k8s.vogelherdweg.de
    tls: true
    tlsSecret: longhorn-internal-k8s-vogelherdweg-de-tls