longhorn:
  defaultSettings:
    createDefaultDiskLabeledNodes: true
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    enabled: true
    host: longhorn.cm4.k8s.vogelherdweg.de
    tls: true
    tlsSecret: longhorn-cm4-k8s-vogelherdweg-de-tls